import Link from "next/link";

export const metadata = {
  title: "Background Removal Guide",
  description: "How to prepare a photo for cleaner AI background removal through FlytheBG's private Hugging Face rembg pipeline, and what to expect from the returned transparent PNG.",
  alternates: { canonical: "/guides/background-removal" },
};

export default function BackgroundRemovalGuide() {
  return (
    <main className="featurePage">
      <section className="pageHero"><div className="shell narrowHero"><span className="eyebrow"><i/> Guide · Background removal</span><h1>How to get a cleaner cutout with private rembg AI.</h1><p>Automatic segmentation works best when the subject has a clear visual boundary. Source sharpness, contrast, fine hair, transparent materials, motion blur, and compression all affect the result.</p></div></section>

      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 01 · Source photo</span><h2>Give the model a clear subject boundary.</h2><p>A studio wall isn&apos;t required, but a sharper original gives rembg more useful edge information.</p></div><div className="principleList"><article><strong>Prefer sharp originals</strong><p>Heavy motion blur, missed focus, very low resolution, and repeated screenshot/compression cycles make hair, fingers, clothing, and product edges harder to separate.</p></article><article><strong>Watch low-contrast edges</strong><p>Dark hair on a dark wall, white fabric against a bright sky, glass, smoke, fur, and semi-transparent materials are naturally difficult cases. A different source photo helps more than repeatedly processing the same difficult image.</p></article><article><strong>Use supported formats</strong><p>FlytheBG accepts PNG, JPEG, and WebP up to 12&nbsp;MB and validates file type, size, and magic-byte signature on the server before inference begins.</p></article></div></div></section>

      <section className="section workflowSection"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 02 · Private processing</span><h2>The token never reaches your browser.</h2><p>Your upload is sent over HTTPS to FlytheBG&apos;s <code>/api/remove-background</code> server route. That route authenticates to the private <code>StackPilotMAX/bg-remover-api</code> Gradio Space using <code>HF_TOKEN</code>, calls <code>/remove_background</code>, and returns the transparent PNG.</p></div><div className="principleList"><article><strong>Server-only secret</strong><p>The Hugging Face token lives in server environment variables (Netlify for production, <code>.env.local</code> for local development) and is never included in client JavaScript.</p></article><article><strong>No browser model download</strong><p>Because inference happens on the Space, the browser does not need to download a large ONNX/WASM model bundle. Results depend on image size, network speed, and current Space load.</p></article><article><strong>Isolated requests</strong><p>Each upload is an independent HTTP request. FlytheBG does not use shared global result state, public filenames, or a persistent image database.</p></article></div></div></section>

      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 03 · Result checks</span><h2>A returned PNG isn&apos;t blindly treated as success.</h2><p>FlytheBG validates the returned content type and size on the server and decodes the PNG in the browser before handing it to the preview/crop/download workflow.</p></div><div className="principleList"><article><strong>Invalid results are rejected</strong><p>Responses that aren&apos;t images or that fall well outside a plausible size are surfaced as errors rather than presented as cutouts.</p></article><article><strong>Inspect fine boundaries</strong><p>Review hair, ears, shoulders, fingers, product handles, and transparent objects before professional use. Automatic segmentation can still make mistakes.</p></article></div></div></section>

      <section className="finalCta"><div className="shell finalCtaInner"><div><span className="eyebrow"><i/> Try the workflow</span><h2>Process one photo through the private rembg pipeline.</h2><p>You get a transparent PNG you can crop and download immediately.</p></div><div className="buttonRow"><Link className="buttonPrimary" href="/remove-background">Open remover <span>↗</span></Link><Link className="buttonSecondary" href="/guides">All guides</Link></div></div></section>
    </main>
  );
}
