import { LegalPage } from "@/components/LegalPage";
import { appConfig } from "@/lib/config";

export const metadata = { title: "FlyThe BG Terms of Use", description: "Terms for FlyThe BG browser-based image, passport-photo, and authorized visible-watermark editing tools.", alternates: { canonical: "/terms" } };

export default function TermsPage(){ return <LegalPage title="Terms of Use" updated="4 September 2026">
<h2>1. Service</h2><p>FlyThe BG provides browser-based image and media utilities including background removal, cropping, passport-photo sheet generation, and supported visible-watermark editing for image and video media. Results are provided as editing outputs and are not guaranteed to perfectly reconstruct every underlying pixel.</p>
<h2>2. Your media and rights</h2><p>You are responsible for having the rights and permissions needed to use media with FlyThe BG. Using the service does not transfer ownership of your image or video to FlyThe BG. Do not remove a watermark, attribution, provenance signal, or other notice when doing so would violate copyright, licensing, privacy, platform rules, applicable law, or another person&apos;s rights.</p>
<h2>3. Gemini, Veo, Meta AI, and third-party ownership</h2><p>Gemini and Veo are Google products and Meta AI is a Meta product. Google, Gemini, Veo, Meta, Meta AI, their names, logos, marks, and related product assets belong to their respective owners. FlyThe BG is independent and does not claim affiliation, sponsorship, endorsement, or ownership of those brands. Provider names in FlyThe BG are used to identify supported source formats.</p>
<h2>4. Visible watermark editing</h2><p>The Gemini/Veo workflow uses calibrated reference assets and reverse-alpha reconstruction adapted from the MIT-licensed <a href="https://github.com/ishara-madu/gemini-watermark-remover">ishara-madu/gemini-watermark-remover</a>. It targets visible pixel overlays only. It does not remove invisible provenance systems such as Google SynthID or Meta Content Seal. Meta&apos;s visible watermark layouts can vary by product generation, so the Meta preset is explicitly editable and should be previewed before export.</p>
<h2>5. Browser AI and third-party software</h2><p>FlyThe BG integrates third-party browser software, model/runtime assets, and hosting or analytics services. Those components may have separate licences, notices, terms, or availability limits. FlyThe BG does not claim ownership of third-party software or model assets. See <a href="/model-disclosure">Model &amp; Open Source Disclosure</a>.</p>
<h2>6. Passport photos</h2><p>The Passport Photo Maker provides sizing, background color, crop positioning, per-copy crop choices, layout, DPI, and print-sheet tools. It does not guarantee acceptance by any passport office, government authority, visa authority, school, employer, or other organization. Always check the current requirements of the authority receiving the photo.</p>
<h2>7. Advertising</h2><p>FlyThe BG may use Google AdSense and Monetag when production configuration, provider requirements, and applicable consent controls allow it. Advertisement placements are intended to remain separate from product controls. Providers may change their policies, formats, or technical requirements.</p>
<h2>8. Availability and future changes</h2><p>FlyThe BG is presented as a production service. Features, supported browser APIs, provider formats, third-party dependencies, limits, and infrastructure may change as the product evolves. The site will update its public documentation when a material change affects processing, privacy, or supported workflows.</p>
<h2>9. No warranty</h2><p>FlyThe BG is provided on an as-available basis. Automated segmentation, watermark candidate geometry, browser video encoding, and pixel reconstruction can make mistakes. Browser memory, device capability, file size, source quality, provider changes, and network availability can affect results. Review outputs before relying on them.</p>
<h2>10. Contact</h2>{appConfig.contactEmail ? <p>Questions about these terms may be sent to <a href={`mailto:${appConfig.contactEmail}`}>{appConfig.contactEmail}</a>.</p> : <p>Questions about these terms may be sent through the contact page.</p>}
</LegalPage>; }
