import { LegalPage } from "@/components/LegalPage";
import { appConfig } from "@/lib/config";

export const metadata = { title: "FlyThe BG Terms of Use", description: "Terms for FlyThe BG browser-based image, passport-photo, and authorized visible-watermark editing tools.", alternates: { canonical: "/terms" } };

export default function TermsPage(){ return <LegalPage title="Terms of Use" updated="6 September 2026">
<h2>1. Service</h2><p>FlyThe BG provides browser-based image and media utilities including background removal, cropping, passport-photo sheet generation, and supported visible-watermark editing for image and video media. Results are provided as editing outputs and are not guaranteed to perfectly reconstruct every underlying pixel.</p>
<h2>2. Your media and rights</h2><p>You are responsible for having the rights and permissions needed to use media with FlyThe BG. Using the service does not transfer ownership of your image or video to FlyThe BG. Do not remove a watermark, attribution, provenance signal, or other notice when doing so would violate copyright, licensing, privacy, platform rules, applicable law, or another person&apos;s rights.</p>
<h2>3. Trademarks, logos, brands, and third-party materials</h2><p>FlyThe BG is independent and does not claim ownership of third-party names, trademarks, service marks, logos, product names, icons, images, software, libraries, model assets, fonts, reference assets, or other protected materials displayed, referenced, linked, or used by the website. All such materials belong to their respective owners and are used only for identification, compatibility, attribution, functionality, or other lawful purposes as applicable.</p><p>Google, Gemini, Veo, Google-related marks and product assets belong to Google and/or its respective rights holders. Meta, Meta AI, and Meta-related marks and product assets belong to Meta Platforms, Inc. and/or its respective rights holders. Instagram and its logo belong to Meta Platforms, Inc. GitHub and its logo belong to GitHub, Inc. Other third-party names and marks appearing on FlyThe BG remain the property of their respective owners. Their appearance on this website does not imply affiliation, sponsorship, endorsement, or partnership unless expressly stated.</p>
<h2>4. Third-party software, models, and open-source assets</h2><p>FlyThe BG incorporates or references third-party software, model/runtime assets, open-source projects, and calibrated reference assets. Those components remain subject to their own licences, copyright notices, terms, and attribution requirements. FlyThe BG does not claim copyright, trademark rights, authorship, or exclusive ownership over those third-party components. The <a href="/model-disclosure">Model &amp; Open Source Disclosure</a> identifies important third-party components used by supported workflows.</p>
<h2>5. Gemini, Veo, Meta AI, and visible watermark editing</h2><p>Gemini and Veo are Google products and Meta AI is a Meta product. Google, Gemini, Veo, Meta, Meta AI, their names, logos, marks, and related product assets belong to their respective owners. FlyThe BG is independent and does not claim affiliation, sponsorship, endorsement, or ownership of those brands. Provider names in FlyThe BG are used to identify supported source formats or workflows.</p><p>The Gemini/Veo workflow uses calibrated reference assets and reverse-alpha reconstruction adapted from the MIT-licensed <a href="https://github.com/ishara-madu/gemini-watermark-remover">ishara-madu/gemini-watermark-remover</a>. It targets visible pixel overlays only. It does not remove invisible provenance systems such as Google SynthID or Meta Content Seal. Meta&apos;s visible watermark layouts can vary by product generation, so the Meta preset is explicitly editable and should be previewed before export.</p>
<h2>6. Browser AI and third-party services</h2><p>FlyThe BG integrates third-party browser software, model/runtime assets, hosting, analytics, advertising, and other services where needed. Those providers and components may have separate licences, notices, terms, trademarks, privacy policies, or availability limits. FlyThe BG does not claim ownership of third-party software, model assets, provider marks, or service infrastructure.</p>
<h2>7. Passport photos</h2><p>The Passport Photo Maker provides sizing, background color, crop positioning, per-copy crop choices, layout, DPI, and print-sheet tools. It does not guarantee acceptance by any passport office, government authority, visa authority, school, employer, or other organization. Always check the current requirements of the authority receiving the photo.</p>
<h2>8. Advertising</h2><p>FlyThe BG may use Google AdSense and Monetag when production configuration, provider requirements, and applicable consent controls allow it. Advertisement placements are intended to remain separate from product controls. Providers may change their policies, formats, or technical requirements.</p>
<h2>9. Availability and future changes</h2><p>FlyThe BG is presented as a production service. Features, supported browser APIs, provider formats, third-party dependencies, limits, and infrastructure may change as the product evolves. The site will update its public documentation when a material change affects processing, privacy, or supported workflows.</p>
<h2>10. No warranty</h2><p>FlyThe BG is provided on an as-available basis. Automated segmentation, watermark candidate geometry, browser video encoding, and pixel reconstruction can make mistakes. Browser memory, device capability, file size, source quality, provider changes, and network availability can affect results. Review outputs before relying on them.</p>
<h2>11. Contact</h2>{appConfig.contactEmail ? <p>Questions about these terms may be sent to <a href={`mailto:${appConfig.contactEmail}`}>{appConfig.contactEmail}</a>.</p> : <p>Questions about these terms may be sent through the contact page.</p>}
</LegalPage>; }
