"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";

type Kind = "image" | "video";
type Provider = "Gemini" | "Meta AI" | "Both / Other";
type Rect = { x:number;y:number;w:number;h:number };
type Point = { x:number;y:number };
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const toPx=(r:Rect,w:number,h:number)=>({x:Math.round(r.x*w/100),y:Math.round(r.y*h/100),w:Math.max(2,Math.round(r.w*w/100)),h:Math.max(2,Math.round(r.h*h/100))});

function inpaint(canvas:HTMLCanvasElement,r:Rect,strength:number){
 const ctx=canvas.getContext("2d",{willReadFrequently:true}); if(!ctx) throw new Error("Canvas is unavailable.");
 const x=clamp(Math.round(r.x),0,canvas.width-2),y=clamp(Math.round(r.y),0,canvas.height-2),w=clamp(Math.round(r.w),2,canvas.width-x),h=clamp(Math.round(r.h),2,canvas.height-y);
 const pad=clamp(Math.round(Math.min(w,h)*.4),5,70),sx=Math.max(0,x-pad),sy=Math.max(0,y-pad),ex=Math.min(canvas.width,x+w+pad),ey=Math.min(canvas.height,y+h+pad),sw=ex-sx,sh=ey-sy;
 const img=ctx.getImageData(sx,sy,sw,sh),orig=new Uint8ClampedArray(img.data),mask=new Uint8Array(sw*sh); const l=x-sx,t=y-sy;
 for(let yy=t;yy<t+h;yy++)for(let xx=l;xx<l+w;xx++)mask[yy*sw+xx]=1;
 const dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]; const work=new Float32Array(orig.length); work.set(orig);
 for(let yy=t;yy<t+h;yy++)for(let xx=l;xx<l+w;xx++){let rr=0,gg=0,bb=0,aa=0,ww=0;for(const[dX,dY]of dirs){for(let s=1;s<=pad+3;s++){const nx=clamp(xx+dX*s,0,sw-1),ny=clamp(yy+dY*s,0,sh-1);if(!mask[ny*sw+nx]){const i=(ny*sw+nx)*4,q=1/(s*s);rr+=orig[i]*q;gg+=orig[i+1]*q;bb+=orig[i+2]*q;aa+=orig[i+3]*q;ww+=q;break;}}}const i=(yy*sw+xx)*4;if(ww){work[i]=rr/ww;work[i+1]=gg/ww;work[i+2]=bb/ww;work[i+3]=aa/ww;}}
 const passes=Math.max(6,Math.min(20,Math.round(Math.min(w,h)/8))); for(let p=0;p<passes;p++){const next=new Float32Array(work);for(let yy=t;yy<t+h;yy++)for(let xx=l;xx<l+w;xx++){if(!mask[yy*sw+xx])continue;let rr=0,gg=0,bb=0,aa=0,n=0;for(const[dX,dY]of dirs){const nx=xx+dX,ny=yy+dY;if(nx<0||ny<0||nx>=sw||ny>=sh)continue;const i=(ny*sw+nx)*4;rr+=work[i];gg+=work[i+1];bb+=work[i+2];aa+=work[i+3];n++;}const i=(yy*sw+xx)*4,q=strength/100;next[i]=work[i]*(1-q)+rr/n*q;next[i+1]=work[i+1]*(1-q)+gg/n*q;next[i+2]=work[i+2]*(1-q)+bb/n*q;next[i+3]=work[i+3]*(1-q)+aa/n*q;}work.set(next);}
 for(let yy=t;yy<t+h;yy++)for(let xx=l;xx<l+w;xx++){if(!mask[yy*sw+xx])continue;const i=(yy*sw+xx)*4;img.data[i]=clamp(Math.round(work[i]),0,255);img.data[i+1]=clamp(Math.round(work[i+1]),0,255);img.data[i+2]=clamp(Math.round(work[i+2]),0,255);img.data[i+3]=clamp(Math.round(work[i+3]),0,255);}ctx.putImageData(img,sx,sy);
}

function detect(canvas:HTMLCanvasElement):Rect|null{
 const max=1200,s=Math.min(1,max/Math.max(canvas.width,canvas.height)),w=Math.max(96,Math.round(canvas.width*s)),h=Math.max(96,Math.round(canvas.height*s)); const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{willReadFrequently:true});if(!ctx)return null;ctx.drawImage(canvas,0,0,w,h);const px=ctx.getImageData(0,0,w,h).data;
 const candidates:Rect[]=[];for(const rw of [.035,.055,.08,.12,.18,.25])for(const rh of [.025,.04,.065,.1,.14]){const cw=Math.max(18,Math.round(w*rw)),ch=Math.max(10,Math.round(h*rh)),step=Math.max(8,Math.round(Math.min(cw,ch)*.6));for(let y=0;y<=h-ch;y+=step)for(let x=0;x<=w-cw;x+=step)candidates.push({x:x/w*100,y:y/h*100,w:cw/w*100,h:ch/h*100});}
 let best:Rect|null=null,bestScore=-Infinity;for(const r of candidates){const q=toPx(r,w,h),x0=q.x,y0=q.y,x1=Math.min(w-1,x0+q.w),y1=Math.min(h-1,y0+q.h);let e=0,n=0,inside=0,out=0;for(let y=y0+1;y<y1-1;y+=2)for(let x=x0+1;x<x1-1;x+=2){const i=(y*w+x)*4,l=px[i]*.2126+px[i+1]*.7152+px[i+2]*.0722,ri=i+4,di=((y+1)*w+x)*4,lr=px[ri]*.2126+px[ri+1]*.7152+px[ri+2]*.0722,ld=px[di]*.2126+px[di+1]*.7152+px[di+2]*.0722;e+=Math.abs(l-lr)+Math.abs(l-ld);inside+=l;n++;}const pad=Math.max(3,Math.round(Math.min(q.w,q.h)*.7));for(let y=Math.max(0,y0-pad);y<Math.min(h,y1+pad);y+=3)for(let x=Math.max(0,x0-pad);x<Math.min(w,x1+pad);x+=3){if(x>=x0&&x<x1&&y>=y0&&y<y1)continue;const i=(y*w+x)*4;out+=px[i]*.2126+px[i+1]*.7152+px[i+2]*.0722;}const score=e/Math.max(1,n)+Math.abs(inside/Math.max(1,n)-out/Math.max(1,n))*.12;if(score>bestScore){bestScore=score;best=r;}}
 c.width=1;c.height=1;return best&&bestScore>10?{x:clamp(best.x-1,0,98),y:clamp(best.y-1,0,98),w:clamp(best.w+2,2,100),h:clamp(best.h+2,2,100)}:null;
}

export function WatermarkRemoverV2(){
 const [kind,setKind]=useState<Kind>("image"),[provider,setProvider]=useState<Provider>("Gemini"),[file,setFile]=useState<File|null>(null),[url,setUrl]=useState(""),[rect,setRect]=useState<Rect|null>(null),[auto,setAuto]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("Upload media. Auto-detect scans the whole image; manual drag is always available."),[strength,setStrength]=useState(92),[scale,setScale]=useState(100),[px,setPx]=useState(0),[py,setPy]=useState(0);
 const img=useRef<HTMLImageElement>(null),video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),drag=useRef<{a:Point;b:Point}|null>(null);
 useEffect(()=>{if(!file)return;const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u)},[file]);
 const selected=useMemo(()=>rect?{...rect,x:clamp(rect.x+px,0,100),y:clamp(rect.y+py,0,100),w:clamp(rect.w*scale/100,1,100),h:clamp(rect.h*scale/100,1,100)}:null,[rect,scale,px,py]);
 function choose(f:File|null){if(!f)return;setFile(f);setKind(f.type.startsWith("video/")?"video":"image");setRect(null);setAuto(false);setMsg("Media loaded. Click Auto-detect or drag over the watermark.");}
 function pointer(e:ReactPointerEvent,up=false){if(!stage.current||busy)return;const b=stage.current.getBoundingClientRect(),p={x:clamp((e.clientX-b.left)/b.width*100,0,100),y:clamp((e.clientY-b.top)/b.height*100,0,100)};if(!up){if(!drag.current)drag.current={a:p,b:p};else drag.current.b=p;const a=drag.current.a;setRect({x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(a.x-p.x),h:Math.abs(a.y-p.y)});setAuto(false);}else{if(drag.current){const a=drag.current.a,r={x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(a.x-p.x),h:Math.abs(a.y-p.y)};drag.current=null;if(r.w>1&&r.h>1){setRect(r);setMsg("Manual selection ready.");}}}}
 function autoDetect(){if(!img.current||!canvas.current)return;const i=img.current,c=canvas.current;c.width=i.naturalWidth;c.height=i.naturalHeight;const ctx=c.getContext("2d");if(!ctx)return;ctx.drawImage(i,0,0,c.width,c.height);const r=detect(c);if(!r){setMsg("No confident watermark candidate found. Drag a box manually over the watermark.");return;}setRect(r);setAuto(true);setScale(100);setPx(0);setPy(0);setMsg("Watermark candidate detected. Inspect the box before export.");}
 async function imageExport(){if(!selected||!img.current||!canvas.current)return;setBusy(true);setMsg("Reconstructing the selected area locally…");try{const i=img.current,c=canvas.current;let w=i.naturalWidth,h=i.naturalHeight;if(Math.max(w,h)>3000){const s=3000/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s)}c.width=w;c.height=h;const ctx=c.getContext("2d");if(!ctx)throw Error("Canvas unavailable.");ctx.drawImage(i,0,0,w,h);inpaint(c,toPx(selected,w,h),strength);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,"image/png",1));if(!blob)throw Error("Could not create the result.");const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`flythebg-${provider.toLowerCase().replaceAll(" ","-")}-watermark-clean.png`;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);setMsg("Done. Cleaned PNG exported locally.");}catch(e){setMsg(e instanceof Error?e.message:"Image processing failed.");}finally{setBusy(false)}}
 async function videoExport(){if(!selected||!video.current||!canvas.current)return;setBusy(true);setMsg("Cleaning every frame locally…");try{const v=video.current,c=canvas.current;await new Promise<void>((res,rej)=>{if(v.readyState>=2)res();else{v.addEventListener("loadeddata",()=>res(),{once:true});v.addEventListener("error",()=>rej(Error("Video could not be decoded.")),{once:true})}});const s=Math.min(1,1920/Math.max(v.videoWidth,v.videoHeight));c.width=Math.round(v.videoWidth*s);c.height=Math.round(v.videoHeight*s);const ctx=c.getContext("2d");if(!ctx)throw Error("Canvas unavailable.");const out=c.captureStream(30),source=(v as HTMLVideoElement&{captureStream?:()=>MediaStream}).captureStream?.();source?.getAudioTracks().forEach(t=>out.addTrack(t));const mime=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error("This browser cannot export WebM.");const rec=new MediaRecorder(out,{mimeType:mime,videoBitsPerSecond:8000000}),chunks:Blob[]=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const stopped=new Promise<void>(r=>rec.addEventListener("stop",()=>r(),{once:true}));rec.start(250);const r=selected,d=v.duration;await v.play();const draw=()=>{if(v.ended){rec.stop();return}ctx.drawImage(v,0,0,c.width,c.height);inpaint(c,toPx(r,c.width,c.height),strength);setMsg(`Cleaning video… ${d?Math.round(v.currentTime/d*100):0}%`);requestAnimationFrame(draw)};draw();await stopped;const blob=new Blob(chunks,{type:mime}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="flythebg-watermark-clean.webm";a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);source?.getTracks().forEach(t=>t.stop());setMsg("Done. Full cleaned video exported as WebM.");}catch(e){setMsg(e instanceof Error?e.message:"Video processing failed.");}finally{setBusy(false)}}
 return <div className="wmV2"><div className="wmControlsTop"><div className="wmSegment"><button className={kind==="image"?"active":""} onClick={()=>setKind("image")}>Image</button><button className={kind==="video"?"active":""} onClick={()=>setKind("video")}>Video</button></div><div className="wmProvider"><span>Source</span><select value={provider} onChange={e=>setProvider(e.target.value as Provider)}><option>Gemini</option><option>Meta AI</option><option>Both / Other</option></select></div><label className="wmUpload">{file?"Replace media":"Upload image or video"}<input type="file" accept="image/*,video/*" onChange={e=>choose(e.target.files?.[0]||null)}/></label></div><div className="wmInstructions"><strong>{auto?"Auto-detected candidate":"Manual selection"}</strong><span>Any aspect ratio. Drag directly over the watermark to select it.</span></div><div className="wmStage" ref={stage} onPointerDown={e=>pointer(e)} onPointerMove={e=>drag.current&&pointer(e)} onPointerUp={e=>pointer(e,true)}>{file&&kind==="image"&&<img ref={img} src={url} alt="Watermark removal preview" draggable={false}/>} {file&&kind==="video"&&<video ref={video} src={url} controls playsInline preload="metadata"/>}{!file&&<div className="wmEmpty">Upload an image or video to begin</div>}{selected&&<div className="wmMask" style={{left:`${selected.x}%`,top:`${selected.y}%`,width:`${selected.w}%`,height:`${selected.h}%`}}><span>{auto?"Auto-detected":"Manual"}</span></div>}</div><div className="wmActionRow"><button className="wmSecondary" onClick={autoDetect} disabled={!file||kind!=="image"||busy}>Auto-detect watermark</button><button className="wmSecondary" onClick={()=>{setRect(null);setAuto(false);setScale(100);setPx(0);setPy(0)}} disabled={busy}>Reset</button><button className="wmPrimary" onClick={kind==="image"?imageExport:videoExport} disabled={!file||!selected||busy}>{busy?"Processing…":`Remove & Export ${kind==="image"?"Image":"Video"}`}</button></div><div className="wmFine"><label>Strength <output>{strength}%</output><input type="range" min="50" max="100" value={strength} onChange={e=>setStrength(+e.target.value)}/></label><label>Size scale <output>{scale}%</output><input type="range" min="50" max="180" value={scale} onChange={e=>setScale(+e.target.value)}/></label><label>Position X <output>{px>0?"+":""}{px}%</output><input type="range" min="-30" max="30" value={px} onChange={e=>setPx(+e.target.value)}/></label><label>Position Y <output>{py>0?"+":""}{py}%</output><input type="range" min="-30" max="30" value={py} onChange={e=>setPy(+e.target.value)}/></label></div><div className="wmMessage" role="status">{msg}</div><canvas ref={canvas} className="wmHiddenCanvas"/><div className="wmNotes"><span>✓ Full-image auto scan</span><span>✓ Manual drag selection</span><span>✓ Any aspect ratio</span><span>✓ No corner-only buttons</span><span>✓ Browser-side processing</span></div></div>