"use client";
import { useEffect,useRef,useState } from "react";
import { detectGeminiWatermark,removeGeminiWatermark,type Detection,type WatermarkSettings } from "@/lib/isharaGeminiWatermarkRemover";
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const blob=(c:HTMLCanvasElement,type="image/png")=>new Promise<Blob>((r,j)=>c.toBlob(x=>x?r(x):j(new Error("Could not encode export.")),type));
export function WatermarkRemoverAuto(){
 const [file,setFile]=useState<File|null>(null),[source,setSource]=useState(""),[clean,setClean]=useState(""),[kind,setKind]=useState<"image"|"video">("image"),[d,setD]=useState<Detection|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[message,setMessage]=useState("Upload an image or video to begin."),[gain,setGain]=useState(.6),[scale,setScale]=useState(1),[ox,setOx]=useState(-128),[oy,setOy]=useState(-128);
 const input=useRef<HTMLInputElement>(null),img=useRef<HTMLImageElement>(null),vid=useRef<HTMLVideoElement>(null),urls=useRef<string[]>([]);useEffect(()=>()=>urls.current.forEach(URL.revokeObjectURL),[]);const keep=(u:string)=>{urls.current.push(u);return u};
 const reset=()=>{setGain(.6);setScale(1);setOx(kind==='image'?-128:-24);setOy(kind==='image'?-128:-24);};
 const choose=(f:File|null)=>{if(!f)return;if(!f.type.startsWith('image/')&&!f.type.startsWith('video/'))return setMessage('Please choose PNG, JPEG, WebP, MP4, WebM, or MOV.');const k=f.type.startsWith('video/')?'video':'image';setFile(f);setKind(k);setSource(keep(URL.createObjectURL(f)));setClean('');setD(null);setProgress(0);setGain(.6);setScale(1);setOx(k==='image'?-128:-24);setOy(k==='image'?-128:-24);setMessage('File loaded. Adjust settings, then process.');};
 const settings=():WatermarkSettings=>({gain,scale,offsetX:ox,offsetY:oy});
 const processImage=async()=>{const el=img.current;if(!el)return;setBusy(true);try{await new Promise<void>(r=>el.complete?r():el.addEventListener('load',()=>r(),{once:true}));const c=document.createElement('canvas');c.width=el.naturalWidth;c.height=el.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});if(!x)throw Error('Canvas unavailable.');x.drawImage(el,0,0);const data=x.getImageData(0,0,c.width,c.height),det=await detectGeminiWatermark(data,c.width,c.height,'image');setD(det);if(!det.matchFound)throw Error('No verified Gemini watermark was detected.');await removeGeminiWatermark(data,det,settings());x.putImageData(data,0,0);setClean(keep(URL.createObjectURL(await blob(c))));setMessage('Image cleaned. Change a setting and process again if alignment needs refinement.');}catch(e){setMessage(e instanceof Error?e.message:'Image processing failed.');}finally{setBusy(false);}};
 const processVideo=async()=>{const v=vid.current;if(!v)return;setBusy(true);setProgress(0);try{if(v.readyState<2)await new Promise<void>((r,j)=>{v.onloadeddata=()=>r();v.onerror=()=>j(Error('Video could not be decoded.'));});const w=v.videoWidth,h=v.videoHeight;if(!w||!h)throw Error('Video has no usable dimensions.');v.currentTime=0;await new Promise<void>(r=>v.readyState>=2?r():v.addEventListener('seeked',()=>r(),{once:true}));const probe=document.createElement('canvas');probe.width=w;probe.height=h;const px=probe.getContext('2d',{willReadFrequently:true});if(!px)throw Error('Canvas unavailable.');px.drawImage(v,0,0,w,h);const det=await detectGeminiWatermark(px.getImageData(0,0,w,h),w,h,'video');setD(det);if(!det.matchFound)throw Error('No verified Gemini watermark was detected in the first frame.');const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});if(!x)throw Error('Canvas unavailable.');const sourceStream=typeof v.captureStream==='function'?v.captureStream():null;const stream=c.captureStream(30);sourceStream?.getAudioTracks().forEach(t=>stream.addTrack(t));const mime=MediaRecorder.isTypeSupported('video/mp4')?'video/mp4':MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000}),chunks:Blob[]=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const stopped=new Promise<void>((r,j)=>{rec.onstop=()=>r();rec.onerror=()=>j(Error('Video recording failed.'));});const duration=v.duration||1;rec.start(250);v.currentTime=0;await v.play();let raf=0;const draw=async()=>{if(v.ended)return;x.drawImage(v,0,0,w,h);const frame=x.getImageData(0,0,w,h);await removeGeminiWatermark(frame,det,settings());x.putImageData(frame,0,0);setProgress(clamp(v.currentTime/duration,0,1));if(!v.ended)raf=requestAnimationFrame(()=>void draw());};raf=requestAnimationFrame(()=>void draw());await new Promise<void>(r=>v.addEventListener('ended',()=>r(),{once:true}));cancelAnimationFrame(raf);rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());setClean(keep(URL.createObjectURL(new Blob(chunks,{type:mime}))));setProgress(1);setMessage(`Video cleaned and exported as ${mime==='video/mp4'?'MP4':'WebM'} with audio when supported.`);}catch(e){setMessage(e instanceof Error?e.message:'Video processing failed.');}finally{setBusy(false);v.pause();}};
 const process=()=>kind==='image'?void processImage():void processVideo();const download=()=>{if(!clean)return;const a=document.createElement('a');a.href=clean;a.download=kind==='image'?'flythebg-clean.png':clean.includes('mp4')?'flythebg-clean.mp4':'flythebg-clean.webm';a.click();};
 return <div style={{maxWidth:1000,margin:'0 auto',padding:18,border:'1px solid #e5e7eb',borderRadius:18,background:'#f8fafc',color:'#111827'}}><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp,video/mp4,video/webm,video/quicktime" onChange={e=>choose(e.target.files?.[0]||null)}/><button onClick={()=>input.current?.click()} style={{width:'100%',padding:28,border:'2px dashed #a5b4fc',borderRadius:14,background:'#fff',fontWeight:800}}>Upload image or video</button>{file&&<><p style={{textAlign:'center',fontWeight:700}}>{busy?`Processing… ${Math.round(progress*100)}%`:message}</p><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 260px',gap:16}}><div style={{background:'#fff',padding:10,borderRadius:12}}>{kind==='image'?<img ref={img} src={source} alt="Original" style={{maxWidth:'100%',maxHeight:520,display:'block',margin:'auto'}}/>:<video ref={vid} src={source} controls playsInline style={{maxWidth:'100%',maxHeight:520,display:'block',margin:'auto'}}/>}</div><div style={{display:'grid',gap:10,alignContent:'start',background:'#fff',padding:14,borderRadius:12}}><label>Strength / Gain: {gain.toFixed(2)}x<input type="range" min="0" max="1" step=".01" value={gain} onChange={e=>setGain(+e.target.value)}/></label><label>Size Scale: {scale.toFixed(2)}x<input type="range" min=".5" max="2" step=".01" value={scale} onChange={e=>setScale(+e.target.value)}/></label><label>Position X: {ox}px<input type="range" min="-512" max="512" value={ox} onChange={e=>setOx(+e.target.value)}/></label><label>Position Y: {oy}px<input type="range" min="-512" max="512" value={oy} onChange={e=>setOy(+e.target.value)}/></label><button onClick={reset}>Reset Sliders</button>{d&&<small>Detected region: {d.width}×{d.height}px · {Math.round(d.score*100)}% match</small>}</div></div><div style={{display:'flex',gap:10,justifyContent:'center',flexWrap:'wrap',marginTop:16}}>{!clean&&<button disabled={busy} onClick={process}>{kind==='image'?'Remove & Export Image':'Remove & Export Video MP4'}</button>}{clean&&<button onClick={download}>Download Clean Result</button>}</div>{clean&&kind==='image'&&<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginTop:16}}><figure><figcaption>Full-frame preview</figcaption><img src={source} alt="Original full frame" style={{width:'100%'}}/></figure><figure><figcaption>Zoomed Original</figcaption><img src={source} alt="Zoomed original" style={{width:'100%',aspectRatio:1,objectFit:'cover',objectPosition:'right bottom'}}/></figure><figure><figcaption>Zoomed Cleaned</figcaption><img src={clean} alt="Zoomed cleaned" style={{width:'100%',aspectRatio:1,objectFit:'cover',objectPosition:'right bottom'}}/></figure></div>}</>}</div>;
}
