import Link from "next/link";

export const metadata = {
  title: "Passport Photo Size, DPI and Pixels Guide | FlyThe BG",
  description: "Understand passport photo physical dimensions, DPI, pixel dimensions, crop framing and why printer scaling matters when creating a measured photo.",
  alternates: { canonical: "/guides/passport-photo-size" },
};

export default function PassportPhotoSizeGuide() {
  return (
    <main className="featurePage">
      <section className="pageHero"><div className="shell narrowHero"><span className="eyebrow"><i/> Guide · Photo dimensions</span><h1>Passport photo size: physical dimensions, DPI, pixels, and printing.</h1><p>“Passport size” is not one universal measurement. The receiving authority determines the required physical width and height, while DPI determines how many pixels are used to represent that physical size in a digital export.</p></div></section>
      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> Physical size</span><h2>Use the authority's dimensions, not a guessed pixel size.</h2><p>If an instruction says a photo must be a particular width and height in millimetres, centimetres, or inches, those physical measurements should drive the workspace. Pixel dimensions are derived from the physical size and selected print resolution.</p></div><div className="principleList"><article><strong>Millimetres and centimetres</strong><p>These describe the printed rectangle. They are the useful starting point when an application specifies a physical photograph size.</p></article><article><strong>Pixels</strong><p>Pixels describe the digital image. The same physical photo can contain different numbers of pixels at different DPI settings.</p></article><article><strong>DPI</strong><p>DPI describes print resolution. It changes the pixel dimensions needed for a given physical size; it does not by itself change the physical dimensions when the printer prints without scaling.</p></article></div></div></section>
      <section className="section workflowSection"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> Framing</span><h2>Move the crop frame over the stationary source image.</h2><p>FlyThe BG's photo maker separates source-photo positioning from the output frame. This makes it easier to keep the original image fixed while deciding exactly which part becomes the measured photo.</p></div><div className="principleList"><article><strong>Keep the subject centered where required</strong><p>Follow the receiving authority's instructions for head size, eye line, margins and facial visibility. The tool provides framing controls but cannot determine every authority's biometric rules.</p></article><article><strong>Do not use the preview as a ruler</strong><p>Browser zoom, monitor density and responsive layout change how large an image appears on screen. The physical output settings are what matter for printing.</p></article><article><strong>Check the source before editing</strong><p>Good focus, even lighting and a suitable background make framing easier. Editing cannot recover detail that is absent from the original photo.</p></article></div></div></section>
      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> Printing</span><h2>Correct file dimensions can still print incorrectly.</h2><p>Printer software often offers automatic scaling. If a measured sheet is scaled to fit the page, every photo rectangle changes size.</p></div><div className="principleList"><article><strong>Choose Actual Size / 100%</strong><p>When your printer and paper setup permit it, disable Fit to Page and similar automatic scaling options.</p></article><article><strong>Respect printable margins</strong><p>Some printers cannot print to the paper edge. The sheet layout should leave enough margin for the actual printer rather than assuming edge-to-edge printing.</p></article><article><strong>Measure a test print</strong><p>Before submitting important photographs, measure one printed rectangle with a ruler. This catches incorrect paper settings and driver scaling.</p></article></div></div></section>
      <section className="section faqSection"><div className="shell"><div className="sectionHeading"><span className="eyebrow"><i/> Size FAQ</span><h2>Common passport-photo measurement questions.</h2></div><div className="landingFaqGrid"><details><summary>Is 35×45 mm the passport size everywhere?</summary><p>No. Different countries, documents and authorities can require different dimensions. Treat 35×45 mm as a specific format, not a universal passport-photo rule.</p></details><details><summary>Does 300 DPI mean the photo is automatically accepted?</summary><p>No. DPI is only one part of digital/print production. Acceptance can also depend on physical size, head position, lighting, background, expression, recency and the authority's file requirements.</p></details><details><summary>Why does the same photo have different pixel dimensions at different DPI?</summary><p>Because DPI changes the number of pixels assigned to each inch of physical output. A higher DPI therefore needs more pixels for the same physical width and height.</p></details></div></div></section>
      <section className="finalCta"><div className="shell finalCtaInner"><div><span className="eyebrow"><i/> Make the measured file</span><h2>Set the physical dimensions, frame the subject, and build the sheet.</h2><p>Use the live browser photo maker after checking the current requirements for your application.</p></div><div className="buttonRow"><Link className="buttonPrimary" href="/features/passport-photo">Open Passport & Visa Photo Maker <span>↗</span></Link><Link className="buttonSecondary" href="/guides">All guides</Link></div></div></section>
    </main>
  );
}
