import type { Metadata } from "next";
import Link from "next/link";
import { AdPlaceholder } from "@/components/AdPlaceholder";
import { HoverFaqList } from "@/components/HoverFaqList";
export const metadata: Metadata = { title: "FlytheBG FAQ: Free Background Remover, Gemini Watermark Remover & Passport Photos", description: "Answers about FlytheBG free background remover, AI background removal, Gemini watermark remover, passport photo maker, privacy, local browser processing, downloads, and advertising.", keywords: ["free background remover", "background remover online", "AI background remover", "Gemini watermark remover", "free Gemini watermark remover", "passport photo maker", "passport size photo", "visa photo maker", "online image tools", "background remover FAQ"], alternates: { canonical: "/faq" } };
const generalFaqs = [
  ["Does FlytheBG upload my working photo to an image-processing server?", "The current background-removal, passport-photo, and watermark-removal workflows are designed to process the working media in browser memory. The page still downloads application, model, runtime, font, video, and advertising assets as needed, but FlytheBG does not intentionally attach your selected media to those asset requests."],
  ["Is there a Gemini watermark remover?", "Yes. The AI Watermark Remover page is explicitly optimized around the search phrase Gemini watermark remover and includes Gemini as a source label. Meta AI is available in the same workspace as a separate label so the two products are not presented as one official service."],
  ["Does the watermark tool support Meta AI too?", "Yes. Choose Meta AI in the source selector. Gemini, Meta AI, Google, and Meta are trademarks and properties of their respective owners. FlytheBG is an independent tool and does not claim affiliation or endorsement."],
  ["Can the watermark tool find a non-moving watermark automatically?", "Yes. Use Auto-detect on the image or on a representative video frame. FlytheBG searches likely edge/corner overlay regions and highlights a candidate for your inspection. It is a local candidate finder, not a guaranteed AI watermark detector, so always check the highlighted box before export."],
  ["Does the watermark remover support full video?", "Yes. The video workflow now processes the clip frame-by-frame in your browser and exports a cleaned WebM file. The selected watermark region stays fixed across the clip, which is best for non-moving overlays. Long or high-resolution videos can use substantial CPU, GPU, and memory."],
  ["Can I prevent a Gemini watermark on future creations?", "If you generate new images inside Google Gemini on the web, you can check Gemini Settings for the current visible/media watermark control and turn it off where Google makes that option available to your account. This only affects future creations; it cannot remove watermarks from already-saved files or Veo videos. Provider settings can change, so follow the current Google/Gemini UI."],
  ["What if I don't like the watermark-removal result?", "Keep the original and inspect the result before publishing. Run Auto-detect again, choose a different corner preset, or adjust the selected area. Detailed backgrounds, gradients, faces, text, and moving scenes can produce artifacts because the tool reconstructs pixels from surrounding content."],
  ["Which AI model does FlytheBG use for background removal?", "FlytheBG uses IMG.LY's browser background-removal package with IS-Net model variants. The remover starts with the smaller quantized model for the faster common path and can use a higher-quality local path on suitable devices."],
  ["Does FlytheBG specifically protect faces, hair, or clothing?", "Yes. In addition to the model's alpha mask and existing edge safeguards, FlytheBG applies a conservative interior-detail check that can restore tiny holes inside already-detected foreground. It is designed to protect likely face and clothing pixels without restoring the outer background silhouette."],
  ["Why can I still see white around a cutout?", "The exported result is a transparent PNG. Some image viewers display transparency as white. FlytheBG also applies a conservative interior protection pass that does not intentionally paint a white border back around the subject. Check the PNG on a checkerboard or colored background when verifying transparency."],
  ["Is the AI model owned by FlytheBG?", "No. The background-removal library, model/runtime assets, and related third-party components are not claimed as FlytheBG property. See the Model & Open Source Disclosure for the current package version and licensing statement."],
  ["How does passport cropping work?", "The source photo stays stationary in the Passport Photo Maker. You move the visible crop frame over the photo, adjust crop zoom/frame size, and then build the print sheet. Individual printed copies can use their own crop-frame settings."],
  ["Does using a passport-photo preset guarantee acceptance?", "No. FlytheBG helps with crop framing, physical dimensions, DPI, layout, and printing, but an issuing authority can impose additional requirements."],
  ["Can I use FlytheBG without an account?", "Yes. The current public tools do not require an account to select media, process supported local workflows, or generate exports."],
  ["Why can the first background-removal run take longer?", "The browser may need to download the AI model and runtime assets before the first inference. Later runs may be faster when those assets are cached."],
  ["Can AdSense and Monetag appear on FlytheBG?", "FlytheBG contains reserved advertisement placements and disabled-by-default configuration for both networks. Real advertising only loads after the required public publisher values are configured."],
  ["Are advertisement areas part of the tool controls?", "No. Reserved ad placements are clearly labelled Advertisement and kept separate from upload, download, navigation, and editing controls."],
] as const;
export default function FaqPage() { return <main className="featurePage faqPage"><section className="pageHero compactHero"><div className="shell narrowHero landingReveal"><span className="eyebrow"><i/> FlytheBG FAQ</span><h1>Answers for free background removal, Gemini watermark tools, passport photos, privacy, and more.</h1><p>Use this page for general questions, then jump directly to the tool-specific pages when you need deeper guidance.</p><div className="faqJumpLinks"><Link href="/remove-background#faq">Free background remover FAQ ↗</Link><Link href="/ai-watermark-remover#faq">Gemini &amp; Meta AI watermark remover FAQ ↗</Link><Link href="/features/passport-photo#faq">Passport photo FAQ ↗</Link><Link href="/model-disclosure">Model &amp; licensing disclosure ↗</Link></div></div><div className="shell pageHeroAd" aria-label="Top advertisement placement"><AdPlaceholder slot="faq-inline-1" format="leaderboard" /></div></section><section className="section faqSection" id="general-faq"><div className="shell faqGrid"><div className="sectionHeading compact landingReveal"><span className="eyebrow"><i/> General questions</span><h2>How FlytheBG works, what it uses, and what it does not claim.</h2><p>Click any question to open or close it. Desktop hover remains available, but click, touch, and keyboard interaction are the primary accessible controls.</p></div><HoverFaqList items={generalFaqs} /></div></section></main>; }
