import type { Metadata } from "next";
import Link from "next/link";
import { AdPlaceholder } from "@/components/AdPlaceholder";
import { HoverFaqList } from "@/components/HoverFaqList";
export const metadata: Metadata = { title: "FlytheBG FAQ: Background Removal, Watermarks & Privacy", description: "Answers about FlytheBG browser AI, background removal, AI watermark-removal media tools, passport-photo framing, privacy, model licensing, downloads, and optional advertising.", alternates: { canonical: "/faq" } };
const generalFaqs = [
  ["Does FlytheBG upload my working photo to an image-processing server?", "The current background-removal, passport-photo, and watermark-removal workflows are designed to process the working media in browser memory. The page still downloads application, model, runtime, font, video, and advertising assets as needed, but FlytheBG does not intentionally attach your selected media to those asset requests."],
  ["Is there a Gemini watermark remover?", "Yes. The AI Watermark Remover page is explicitly optimized around the search phrase Gemini watermark remover and includes Gemini as a source label. Meta AI is available in the same workspace as a separate label so the two products are not presented as one official service."],
  ["Does the watermark tool support Meta AI too?", "Yes. Choose Meta AI in the source selector. Gemini, Meta AI, Google, and Meta are trademarks and properties of their respective owners. FlytheBG is an independent tool and does not claim affiliation or endorsement."],
  ["Does the watermark remover support video?", "The workspace accepts video and can clean a local preview frame. Full frame-by-frame reconstruction can be memory-intensive, so FlytheBG deliberately avoids silently consuming excessive browser resources."],
  ["Can I prevent a Gemini watermark on future creations?", "If Google Gemini on the web provides a visible Media watermark setting for your account, you can check Gemini Settings and turn that visible option off for future generations. Provider controls can change, and this does not remove a watermark from media you already saved."],
  ["What if I don't like the watermark-removal result?", "Keep the original and inspect the result before publishing. You can choose a different corner preset or a more accurate selected area. Detailed backgrounds, gradients, faces, text, and moving scenes can produce artifacts because the tool reconstructs pixels from surrounding content."],
  ["Which AI model does FlytheBG use for background removal?", "FlytheBG uses IMG.LY's browser background-removal package with IS-Net model variants. The remover starts with the smaller quantized model for the faster common path and can use a higher-quality local path on suitable devices."],
  ["Does FlytheBG specifically protect hair or white clothing?", "FlytheBG adds local safeguards around the background-removal model result. These reduce some errors but do not guarantee perfect hair, clothing, or edge reconstruction."],
  ["Is the AI model owned by FlytheBG?", "No. The background-removal library, model/runtime assets, and related third-party components are not claimed as FlytheBG property. See the Model & Open Source Disclosure for the current package version and licensing statement."],
  ["How does passport cropping work?", "The source photo stays stationary in the Passport Photo Maker. You move the visible crop frame over the photo, adjust crop zoom/frame size, and then build the print sheet. Individual printed copies can use their own crop-frame settings."],
  ["Does using a passport-photo preset guarantee acceptance?", "No. FlytheBG helps with crop framing, physical dimensions, DPI, layout, and printing, but an issuing authority can impose additional requirements."],
  ["Can I use FlytheBG without an account?", "Yes. The current public tools do not require an account to select media, process supported local workflows, or generate exports."],
  ["Why can the first background-removal run take longer?", "The browser may need to download the AI model and runtime assets before the first inference. Later runs may be faster when those assets are cached."],
  ["Can AdSense and Monetag appear on FlytheBG?", "FlytheBG contains reserved advertisement placements and disabled-by-default configuration for both networks. Real advertising only loads after the required public publisher values are configured."],
  ["Are advertisement areas part of the tool controls?", "No. Reserved ad placements are clearly labelled Advertisement and kept separate from upload, download, navigation, and editing controls."],
] as const;
export default function FaqPage() { return <main className="featurePage faqPage"><section className="pageHero compactHero"><div className="shell narrowHero landingReveal"><span className="eyebrow"><i/> FlytheBG FAQ</span><h1>Answers for background removal, AI watermark tools, privacy, and more.</h1><p>Use this page for general questions, then jump directly to the tool-specific pages when you need deeper guidance.</p><div className="faqJumpLinks"><Link href="/remove-background#faq">Background remover FAQ ↗</Link><Link href="/ai-watermark-remover#faq">AI watermark remover FAQ ↗</Link><Link href="/features/passport-photo#faq">Passport photo FAQ ↗</Link><Link href="/model-disclosure">Model & licensing disclosure ↗</Link></div></div><div className="shell pageHeroAd" aria-label="Top advertisement placement"><AdPlaceholder slot="faq-inline-1" format="leaderboard" /></div></section><section className="section faqSection" id="general-faq"><div className="shell faqGrid"><div className="sectionHeading compact landingReveal"><span className="eyebrow"><i/> General questions</span><h2>How FlytheBG works, what it uses, and what it does not claim.</h2><p>Click any question to open or close it. Desktop hover remains available, but click, touch, and keyboard interaction are the primary accessible controls.</p></div><HoverFaqList items={generalFaqs} /></div></section></main>; }
