import Link from "next/link";

export const metadata = {
  title: "About FlytheBG: Browser Image Tools",
  description: "Learn how FlytheBG's browser-first image tools work, what the production architecture does with image data, and what the product does and does not promise.",
  alternates: { canonical: "/about" },
  openGraph: {
    title: "About FlytheBG: Browser-First Image Tools",
    description: "Learn how FlytheBG's browser-first background removal and passport-photo tools work, including image processing, privacy behavior, and technical limits.",
    url: "/about",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "About FlytheBG: Browser-First Image Tools",
    description: "Learn how FlytheBG's browser image tools work and what the product does and does not promise.",
  },
};

export default function AboutPage() {
  return (
    <main className="featurePage">
      <section className="pageHero"><div className="shell narrowHero"><span className="eyebrow"><i/> About FlytheBG</span><h1>A browser-first image toolkit built around useful, explainable workflows.</h1><p>FlytheBG is a web application for background removal, transparent PNG preparation, cropping, and measured passport-photo sheet creation. The current production version is intentionally narrow: it documents the tools that are actually live instead of presenting unfinished utilities as finished products.</p></div></section>
      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> Why it exists</span><h2>Make common image tasks easier without requiring an image-processing account or server upload.</h2><p>Many quick image tasks do not require a permanent account, cloud project, or stored image library. FlytheBG focuses on workflows that modern browsers can perform locally while still explaining the tradeoffs that come with browser-based AI.</p></div><div className="principleList"><article><strong>Background removal</strong><p>The remover creates a transparent foreground cutout using IMG.LY in the browser. It is intended for portraits, products, social graphics, presentation assets, and similar cases where a transparent PNG is useful.</p></article><article><strong>Passport-photo layout</strong><p>The Passport Photo Maker helps convert real-world photo dimensions into a DPI-aware digital output, frame the subject, repeat copies, and arrange them on a print sheet. It does not replace the issuing authority’s official rules.</p></article><article><strong>Clear product guidance</strong><p>Each tool includes explanations of the current processing path, quality limitations, privacy behavior, and practical usage details so the page still has value before a visitor selects a file.</p></article></div></div></section>
      <section className="section toolInfoSection"><div className="shell"><div className="sectionHeading"><span className="eyebrow"><i/> Current production architecture</span><h2>What happens when you use the image tools.</h2><p>The production web app is exported as static HTML, CSS, and JavaScript. The browser downloads the application and, when background removal is requested, loads the model/runtime assets needed to process the selected image locally.</p></div><div className="infoCards"><article><span>Image selection</span><h2>Your source image enters browser memory.</h2><p>Native file selection, drag and drop, or paste provides the image to the page. FlytheBG validates supported file type and size before starting the more expensive background-removal work.</p></article><article><span>Model processing</span><h2>The smaller quantized model runs directly.</h2><p>The current remover uses IMG.LY’s quantized IS-Net model for automatic background removal. FlytheBG no longer downloads the much larger FP16 model first, reducing startup bandwidth and browser memory pressure for both live image workflows.</p></article><article><span>Output</span><h2>The browser builds the downloadable result.</h2><p>Transparent cutouts, crop output, passport-photo framing, sheet composition, and PNG encoding are performed in the browser. FlytheBG does not intentionally require an image-processing API for the current live tools.</p></article></div></div></section>
      <section className="section workflowSection"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> What FlytheBG does not promise</span><h2>Useful tools still have technical limits.</h2><p>The site avoids guarantees that an automatic model, a browser, or a document-layout tool cannot reliably make.</p></div><div className="principleList"><article><strong>No perfect segmentation guarantee</strong><p>Fine hair, fur, glass, smoke, reflections, similar foreground/background colors, motion blur, and very low-resolution images can produce imperfect masks. Important cutouts should be checked at full size.</p></article><article><strong>No passport acceptance guarantee</strong><p>Physical dimensions are only one part of document-photo compliance. Head position, expression, recency, background, clothing, editing rules, digital file requirements, and printing rules can differ by authority.</p></article><article><strong>No absolute privacy or availability guarantee</strong><p>Browser-first processing reduces the need to send image bytes to a FlytheBG inference server, but no website can guarantee absolute security, uninterrupted service, or control over browser caches, downloaded files, extensions, screenshots, or the visitor’s device.</p></article><article><strong>No hidden unfinished catalog</strong><p>The public feature catalog is limited to live tools and explanatory pages. New utilities should only be added to the public catalog when they provide a complete, usable workflow and supporting documentation.</p></article></div></div></section>
      <section className="section toolInfoSection"><div className="shell infoCards"><article><span>Advertising during review</span><h2>The current review build does not render ad units.</h2><p>FlytheBG currently keeps the AdSense account verification metadata and build-generated seller record without intentionally loading Auto Ads JavaScript or placing ad units inside the image workspaces. Advertising should only be introduced after approval with placements that do not cover, interrupt, or replace the publisher content.</p></article><article><span>Privacy details</span><h2>Read the image and advertising data policy.</h2><p>The Privacy & AI Policy describes the current browser image lifecycle, IMG.LY model/runtime assets, working-memory cleanup, generated output, and how advertising-related processing may change if ads are enabled later.</p><Link className="textLink" href="/privacy">Read Privacy & AI Policy ↗</Link></article><article><span>Questions</span><h2>Contact FlytheBG directly.</h2><p>Product support, privacy questions, legal notices, and security reports use the contact channel published on the site. When reporting an image issue, a written description is usually enough to begin troubleshooting.</p><Link className="textLink" href="/contact">Contact FlytheBG ↗</Link></article></div></section>
    </main>
  );
}
