import Link from "next/link";

export const metadata = {
  title: "How Browser Video Compression Works | FlyThe BG",
  description: "Learn how FlyThe BG compresses supported videos in your browser, how quality and target-size controls work, and why final file size can vary.",
  alternates: { canonical: "/guides/video-compression" },
};

export default function VideoCompressionGuide() {
  return (
    <main className="featurePage">
      <section className="pageHero"><div className="shell narrowHero"><span className="eyebrow"><i/> Guide · Video compression</span><h1>How to compress a video in your browser without uploading the source for compression.</h1><p>FlyThe BG uses browser media capabilities to decode and encode supported videos locally. This guide explains what the quality controls actually do, why target size is best-effort, and when a phone or browser may reach its limits.</p></div></section>
      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 01 · Choose a target</span><h2>Start with the result you actually need.</h2><p>Quality, output resolution, and target size solve different problems. A smaller resolution can reduce both pixel workload and bitrate requirements, while quality changes the compression target at the selected resolution.</p></div><div className="principleList"><article><strong>High, Medium, Low</strong><p>The quality presets select different starting bitrate targets. They are not promises of a particular percentage reduction because source codec, motion, duration, audio, and scene complexity all affect the final file.</p></article><article><strong>Resolution</strong><p>Reducing a 4K recording to 1080p can remove a large amount of pixel data. Keep the original resolution when detail matters more than file size.</p></article><article><strong>Target size</strong><p>A target such as 25 MB is used to calculate a starting video bitrate from duration. The final MP4 can still be above or below the target because encoding and container overhead are not perfectly predictable.</p></article></div></div></section>
      <section className="section workflowSection"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 02 · What happens locally</span><h2>The browser performs the media work.</h2><p>The compressor uses supported browser decoding and encoding APIs rather than sending the selected video to a FlyThe BG compression endpoint.</p></div><div className="principleList"><article><strong>Decode</strong><p>The browser reads the source container and decodes video frames. Compatibility is feature-detected before a job begins where possible.</p></article><article><strong>Encode</strong><p>Supported browsers encode an H.264 video stream and package it into an MP4 output. Audio and container behaviour can affect the resulting size.</p></article><article><strong>Measure</strong><p>FlyThe BG reports the actual output size after encoding instead of pretending the requested target was achieved exactly.</p></article><article><strong>Download</strong><p>The resulting file is exposed as a browser download. Your browser, operating system, extensions, and download folder can retain their own copies outside the page.</p></article></div></div></section>
      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 03 · Better compression choices</span><h2>Use the smallest change that solves the problem.</h2><p>For sharing a phone recording, reducing resolution is often more useful than aggressively lowering quality. For archive storage, preserve resolution and choose a moderate quality setting.</p></div><div className="principleList"><article><strong>Short social clip</strong><p>Try 1080p or 720p with Medium quality when the destination already recompresses uploads.</p></article><article><strong>Large camera recording</strong><p>Reduce resolution first if the destination does not need the original pixel dimensions.</p></article><article><strong>Exact upload limit</strong><p>Leave headroom below the platform limit because an exact final size cannot be guaranteed by a target-size encoder.</p></article><article><strong>Long or high-resolution video</strong><p>Expect more CPU, memory, battery, and time. A browser tab can be suspended or the device can run out of resources on unusually large jobs.</p></article></div></div></section>
      <section className="section faqSection"><div className="shell"><div className="sectionHeading"><span className="eyebrow"><i/> Video compression FAQ</span><h2>Know the limits before you start.</h2></div><div className="landingFaqGrid"><details><summary>Does the compressor upload my video?</summary><p>The compression workflow is designed to decode and encode the selected video in browser memory rather than sending it to a FlyThe BG compression endpoint. Other site features such as advertising or analytics can make separate requests, as described in the Privacy Policy.</p></details><details><summary>Why is the final size not exactly my target?</summary><p>The target is a bitrate calculation, not a container-level guarantee. Keyframes, motion complexity, audio, codec behaviour, metadata and MP4 overhead all affect the final byte count.</p></details><details><summary>Why can compression take a long time?</summary><p>Video encoding is CPU-intensive. Longer videos, higher resolutions and slower devices require more work, and browser scheduling can reduce throughput when the tab is backgrounded.</p></details><details><summary>What if my browser is not supported?</summary><p>FlyThe BG checks browser codec capabilities and can report that a local path is unavailable instead of pretending that a conversion will work.</p></details></div></div></section>
      <section className="finalCta"><div className="shell finalCtaInner"><div><span className="eyebrow"><i/> Compress locally</span><h2>Make a smaller MP4 and inspect the real output size.</h2><p>Use the live browser compressor for supported videos.</p></div><div className="buttonRow"><Link className="buttonPrimary" href="/tools/video-compressor">Open Video Compressor <span>↗</span></Link><Link className="buttonSecondary" href="/guides">All guides</Link></div></div></section>
    </main>
  );
}
