import Link from "next/link";

export const metadata = {
  title: "Passport Photo Printing Guide",
  description: "How FlytheBG converts physical photo dimensions into pixels, frames a subject, fills a print sheet, and exports at a measured DPI.",
  alternates: { canonical: "/guides/passport-photo" },
};

export default function PassportPhotoGuide() {
  return (
    <main className="featurePage">
      <section className="pageHero"><div className="shell narrowHero"><span className="eyebrow"><i/> Guide · Passport photos</span><h1>How to build a measured passport-photo print sheet.</h1><p>Passport and ID rules vary by authority. FlytheBG handles production mechanics—physical dimensions, framing, background color, copies, paper size, and PNG export—but the receiving authority decides whether a photo is acceptable.</p></div></section>

      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 01 · Size</span><h2>Start with the official physical dimensions.</h2><p>Enter the required width and height in centimetres, millimetres, or inches. FlytheBG converts those measurements into pixels using the selected DPI.</p></div><div className="principleList"><article><strong>Physical size comes first</strong><p>A photo that looks correct on screen can still print at the wrong size. The important inputs are physical width and height together with print resolution.</p></article><article><strong>300 DPI is a practical default</strong><p>For common paper sizes, 300 DPI provides substantial print resolution without creating unnecessarily huge browser canvases. A 600 DPI request can be reduced by the memory guard if the resulting sheet would be too large.</p></article><article><strong>Verify the authority's rule</strong><p>Do not assume one popular passport-photo size applies to every country, visa, licence, school, employer, or ID card.</p></article></div></div></section>

      <section className="section workflowSection"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 02 · Subject and background</span><h2>Frame the person before filling the sheet.</h2><p>The Passport Photo Maker lets you drag the subject, adjust zoom, and choose a photo background color. If background removal is enabled, the same smaller quantized IMG.LY browser model runs first.</p></div><div className="principleList"><article><strong>Use framing deliberately</strong><p>Zoom and reposition so the face and shoulders match the target specification. FlytheBG does not guarantee head height, eye line, expression, pose, clothing, lighting, or biometric compliance.</p></article><article><strong>Color stays inside each photo</strong><p>The chosen photo background is painted inside every passport-photo rectangle. The surrounding print paper remains white, so the selected color does not cover the entire page.</p></article><article><strong>Review the cutout</strong><p>If the background was removed, inspect hair and shoulder edges before printing. A correctly measured sheet cannot repair a poor source image or an authority-rule violation.</p></article></div></div></section>

      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 03 · Paper and copies</span><h2>Let sheet capacity determine how many copies fit.</h2><p>Paper size, margins, gaps, and individual photo dimensions determine the number of copies that can fit without drawing outside the paper.</p></div><div className="principleList"><article><strong>Use Fill sheet when useful</strong><p>The Fill sheet control sets the requested copies to the calculated capacity instead of asking the browser to create copies outside the available layout.</p></article><article><strong>Leave practical cutting space</strong><p>A small gap can make trimming easier. Larger margins reduce capacity but may help printers that cannot print edge-to-edge.</p></article><article><strong>Choose the paper you will actually use</strong><p>A4, 4×6-inch photo paper, US Letter, and custom paper have different capacities and aspect ratios.</p></article></div></div></section>

      <section className="section workflowSection"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> 04 · Print</span><h2>Print at Actual Size / 100%.</h2><p>The PNG contains the requested physical layout at the reported DPI, but printer software can still rescale the file unless fit-to-page behaviour is disabled.</p></div><div className="principleList"><article><strong>Avoid automatic Fit</strong><p>Options such as Fit, Shrink to printable area, or Scale to page can change the photo dimensions. Prefer Actual Size or 100% when the printer and paper setup allow it.</p></article><article><strong>Measure a test print</strong><p>Before producing many copies, print one sheet and measure a photo rectangle with a ruler. This catches driver scaling and wrong-paper settings.</p></article><article><strong>Keep the current requirements nearby</strong><p>Compare the final print with the receiving authority's current written specification before submission.</p></article></div></div></section>

      <section className="finalCta"><div className="shell finalCtaInner"><div><span className="eyebrow"><i/> Build a sheet</span><h2>Frame one photo and fill the page.</h2><p>The live maker performs layout and PNG export in your browser.</p></div><div className="buttonRow"><Link className="buttonPrimary" href="/features/passport-photo">Open Passport Maker <span>↗</span></Link><Link className="buttonSecondary" href="/guides">All guides</Link></div></div></section>
    </main>
  );
}
