type ToolId = "remove-bg" | "image-compressor" | "video-compressor";
type Route = "/" | "/remove-bg" | "/image-compressor" | "/video-compressor" | "/features" | "/about" | "/faq" | "/privacy" | "/terms" | "/contact";

const VIDEO = "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260912_104303_0c6d60b2-9353-408e-9449-585108a22fb5.mp4";
const POSTER = "https://d2ol7oe51mr4n9d.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/130837c4-0244-4f37-9c61-8d801d93fd29.jpg";
const state: Record<ToolId, boolean> = {"remove-bg":false,"image-compressor":false,"video-compressor":false};

const esc = (value: string): string => value.replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c] || c));

function shell(content: string, title: string): string {
  document.title = title;
  return `<div class="notice">By using FlyThe BG, you acknowledge and accept our <a href="/privacy">Privacy Policy</a> and <a href="/terms">Terms</a>.</div>
  <header class="nav"><a class="brand" href="/" aria-label="FlyThe BG home"><span class="brand-mark">F</span><span>FlyThe BG</span></a><nav><a href="/features">Tools</a><a href="/about">About</a><a href="/faq">FAQ</a><a href="/contact">Contact</a></nav></header>${content}
  <footer class="footer"><div><strong>FlyThe BG</strong><span>Privacy-first media utilities.</span></div><nav><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/faq">FAQ</a><a href="/contact">Contact</a></nav><small>© 2026 FlyThe BG · AGPL-3.0 · Independent project · stackpilotfe@outlook.com</small></footer>`;
}

function toolPage(id: ToolId, title: string, description: string, accept: string, note: string, privacyNote: string): string {
  const consent = id === "remove-bg" ? `<label class="consent"><input type="checkbox" data-consent="remove-bg"><span>I understand that this image will be sent to FlyThe BG's protected background-removal processor for the requested result.</span></label>` : "";
  return shell(`<main class="tool-page"><div class="tool-intro"><p class="eyebrow">FLYTHE BG · ${id === "remove-bg" ? "01" : id === "image-compressor" ? "02" : "03"}</p><h1>${title}</h1><p>${description}</p></div><section class="tool-workspace"><div class="workspace-head"><span>DROP YOUR FILE</span><span>${note}</span></div>${consent}<label class="big-dropzone"><input data-input="${id}" type="file" accept="${accept}"><span class="upload-arrow">↑</span><strong>Choose a file</strong><small>or tap here to browse your device</small><em>${note}</em></label><p class="status" role="status" aria-live="polite" data-status="${id}">Ready when you are.</p></section><p class="processing-note">${privacyNote}</p></main>`, `${title} — FlyThe BG`);
}

function home(): string {
  return shell(`<main><section class="hero"><video class="hero-video" autoplay muted loop playsinline preload="metadata" poster="${POSTER}" aria-hidden="true"><source src="${VIDEO}" type="video/mp4"></video><div class="hero-shade"></div><div class="hero-copy"><p class="eyebrow">FLYTHE BG</p><h1 class="calligraphy">Create.<br>Clean.<br>Fly.</h1><p class="hero-sub">A focused collection of privacy-first tools for images and video.</p><div class="actions"><a class="button primary" href="/features">Get started</a><a class="button ghost" href="#tools">Explore tools</a></div></div></section>
  <section id="tools" class="section"><div class="center-heading"><p class="eyebrow">TOOLS</p><h2>One tool. One page.<br>One clear workflow.</h2><p>Choose exactly what you need. Your file handling is explained before processing.</p></div><div class="tool-links"><a href="/remove-bg"><span>01</span><div><b>Remove Background</b><small>AI-assisted background removal</small></div><strong>↗</strong></a><a href="/image-compressor"><span>02</span><div><b>Compress Image</b><small>Local browser compression</small></div><strong>↗</strong></a><a href="/video-compressor"><span>03</span><div><b>Compress Video</b><small>Local browser compression</small></div><strong>↗</strong></a></div></section>
  <section class="section centered-section"><p class="eyebrow">BUILT AROUND DATA MINIMISATION</p><h2>Your browser does more.<br>Our server does less.</h2><p>Image and video compression stay on your device. Only background removal needs the protected server route.</p></section></main>`, "FlyThe BG — Privacy-first media tools");
}

function features(): string { return shell(`<main class="page"><div class="page-hero center-heading"><p class="eyebrow">GET STARTED</p><h1>Choose your tool.</h1><p>Each tool now has its own dedicated workspace, instructions and processing boundary.</p></div><div class="tool-links"><a href="/remove-bg"><span>01</span><div><b>Remove Background</b><small>Protected AI processing · PNG/JPG/WEBP · 15 MB</small></div><strong>Open ↗</strong></a><a href="/image-compressor"><span>02</span><div><b>Image Compressor</b><small>Runs locally in your browser</small></div><strong>Open ↗</strong></a><a href="/video-compressor"><span>03</span><div><b>Video Compressor</b><small>Runs locally with MediaRecorder</small></div><strong>Open ↗</strong></a></div></main>`, "Get Started — FlyThe BG"); }

function about(): string { return shell(`<main class="page prose"><p class="eyebrow">ABOUT FLYTHE BG</p><h1>Simple tools. Clear boundaries.</h1><p>FlyThe BG is an independent project focused on practical media utilities with data minimisation as a design goal.</p><h2>How it works</h2><p>Compression is performed locally in your browser. Background removal uses a protected server route so the private AI credential never reaches your device.</p><h2>Independent project</h2><p>FlyThe BG is currently not operated as a registered company or business entity. Project communication: <a href="mailto:stackpilotfe@outlook.com">stackpilotfe@outlook.com</a>.</p></main>`, "About — FlyThe BG"); }

function faq(): string { return shell(`<main class="page prose"><p class="eyebrow">FAQ</p><h1>Questions, answered plainly.</h1><details open><summary>Which tools upload my files?</summary><p>Background removal requires a protected network request. Image and video compression are designed to stay inside your browser.</p></details><details><summary>Do you store uploaded images?</summary><p>FlyThe BG does not intentionally maintain a persistent user image library. The configured AI processor may have its own operational policies, which the project operator must configure appropriately.</p></details><details><summary>Why does background removal say it is not configured?</summary><p>The Cloudflare Worker requires HF_ACCESS_TOKEN, HF_SPACE_URL and HF_SPACE_API secrets. These must be configured in the production Cloudflare environment; they are never placed in the website code.</p></details><details><summary>Can I use the tools without an account?</summary><p>Yes. No FlyThe BG account is required.</p></details></main>`, "FAQ — FlyThe BG"); }

function privacy(): string { return shell(`<main class="page prose legal"><p class="eyebrow">PRIVACY</p><h1>Privacy Policy</h1><p class="muted">Effective: 21 September 2026 · India-focused notice</p><p>FlyThe BG is an independent project. This notice explains intended handling of digital personal data and is written with the Digital Personal Data Protection Act, 2023 and notified Digital Personal Data Protection Rules, 2025 in mind. It is not a legal opinion.</p><h2>Data and purpose</h2><p>Background-removal images are received only when you deliberately submit them, for the purpose of producing the requested result. Contact details are used to respond to messages, privacy requests and security reports. Normal technical connection data may be processed by infrastructure providers for delivery and security.</p><h2>Local compression</h2><p>Image and video compression are designed to run locally in your browser, so the original file does not need to be uploaded to FlyThe BG.</p><h2>Background removal</h2><p>Submitted images pass through a same-origin Cloudflare Worker and are forwarded to the project's configured private AI processor. The Hugging Face credential remains server-side.</p><h2>Consent and withdrawal</h2><p>The background-removal page displays a purpose-specific notice and requires affirmative confirmation before upload. You can stop future processing by not submitting an image. For requests concerning personal data under our control, contact <a href="mailto:stackpilotfe@outlook.com">stackpilotfe@outlook.com</a>.</p><h2>Children</h2><p>The DPDP Act treats a person under 18 as a child. Do not submit a child's personal image unless the applicable lawful requirements and permissions have been satisfied.</p><h2>Retention and security</h2><p>The project is designed not to maintain a persistent image repository. Security controls include HTTPS, server-side secrets, request validation and no-store API responses. Infrastructure providers may process limited operational records under their configurations and policies.</p><h2>Rights and complaints</h2><p>Subject to applicable law, you may have rights concerning access, correction, erasure, consent withdrawal and grievances. Contact the project first at <a href="mailto:stackpilotfe@outlook.com">stackpilotfe@outlook.com</a>. Applicable law may provide additional grievance routes.</p><h2>Changes</h2><p>This notice may be updated as the project, providers or legal requirements change.</p></main>`, "Privacy Policy — FlyThe BG"); }

function terms(): string { return shell(`<main class="page prose legal"><p class="eyebrow">TERMS</p><h1>Terms of Service</h1><p class="muted">Effective: 21 September 2026</p><p>FlyThe BG is an independent project, not currently operated as a registered company or business entity.</p><h2>Use</h2><p>Use the tools lawfully and only with content you are permitted to process. Do not use them to infringe rights or facilitate unlawful activity.</p><h2>Your content</h2><p>You retain your rights in files you submit and are responsible for permissions needed to process them.</p><h2>Results</h2><p>AI-assisted results can be imperfect. Review outputs before important use.</p><h2>Availability</h2><p>The project may change, be rate-limited or become unavailable as infrastructure evolves.</p><h2>Contact</h2><p><a href="mailto:stackpilotfe@outlook.com">stackpilotfe@outlook.com</a></p></main>`, "Terms — FlyThe BG"); }

function contact(): string { return shell(`<main class="page prose"><p class="eyebrow">CONTACT</p><h1>Talk to the project.</h1><p>For privacy requests, security reports, feedback or project communication:</p><a class="contact-card" href="mailto:stackpilotfe@outlook.com"><span>Email</span><strong>stackpilotfe@outlook.com</strong></a></main>`, "Contact — FlyThe BG"); }

function normalizePath(): Route {
  const p = window.location.pathname.replace(/\/+$/, "") || "/";
  const routes: Record<string,Route> = {"/":"/","/remove-bg":"/remove-bg","/image-compressor":"/image-compressor","/video-compressor":"/video-compressor","/features":"/features","/about":"/about","/faq":"/faq","/privacy":"/privacy","/terms":"/terms","/contact":"/contact"};
  return routes[p] || "/";
}

function downloadBlob(blob: Blob, filename: string): void { const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=filename; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
function updateStatus(tool: ToolId, message: string): void { const el=document.querySelector<HTMLElement>(`[data-status="${tool}"]`); if(el) el.textContent=message; }

async function removeBackground(file: File): Promise<void> {
  updateStatus("remove-bg","Uploading to the protected processor…");
  const response=await fetch("/api/remove-bg",{method:"POST",headers:{"Content-Type":file.type},body:file});
  if(!response.ok){let message="Background removal failed."; try{const data=await response.json() as {error?:string}; if(data.error) message=data.error;}catch{} throw new Error(message);}
  downloadBlob(await response.blob(),file.name.replace(/\.[^.]+$/,"")+"-no-bg.png"); updateStatus("remove-bg","Done — transparent PNG downloaded.");
}
async function compressImage(file: File): Promise<void> {
  updateStatus("image-compressor","Processing locally…"); const bitmap=await createImageBitmap(file); const maxSide=2400; const scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)); const canvas=document.createElement("canvas"); canvas.width=Math.max(1,Math.round(bitmap.width*scale)); canvas.height=Math.max(1,Math.round(bitmap.height*scale)); const ctx=canvas.getContext("2d"); if(!ctx) throw new Error("Canvas is unavailable."); ctx.drawImage(bitmap,0,0,canvas.width,canvas.height); bitmap.close(); const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error("Compression failed.")),"image/jpeg",.72)); downloadBlob(blob,file.name.replace(/\.[^.]+$/,"")+"-compressed.jpg"); updateStatus("image-compressor","Done — original stayed in your browser.");
}
async function compressVideo(file: File): Promise<void> {
  if(!("MediaRecorder" in window)) throw new Error("MediaRecorder is unavailable in this browser."); updateStatus("video-compressor","Processing locally…"); const source=document.createElement("video"); source.muted=true; source.playsInline=true; source.src=URL.createObjectURL(file); await new Promise<void>((resolve,reject)=>{source.onloadedmetadata=()=>resolve();source.onerror=()=>reject(new Error("Video could not be read."));}); const canvas=document.createElement("canvas"); const scale=Math.min(1,1280/Math.max(1,source.videoWidth)); canvas.width=Math.max(2,Math.round(source.videoWidth*scale)); canvas.height=Math.max(2,Math.round(source.videoHeight*scale)); const ctx=canvas.getContext("2d"); if(!ctx) throw new Error("Video canvas is unavailable."); const stream=canvas.captureStream(30); const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm"; const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2000000}); const chunks:Blob[]=[]; recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)}; const done=new Promise<void>((resolve,reject)=>{recorder.onstop=()=>resolve();recorder.onerror=()=>reject(new Error("Video compression failed."));}); recorder.start(250); await source.play(); const draw=()=>{if(source.ended){recorder.stop();return;}ctx.drawImage(source,0,0,canvas.width,canvas.height);if(source.duration)updateStatus("video-compressor",`Processing locally… ${Math.min(99,Math.round(source.currentTime/source.duration*100))}%`);requestAnimationFrame(draw)};draw();await done;URL.revokeObjectURL(source.src);downloadBlob(new Blob(chunks,{type:"video/webm"}),file.name.replace(/\.[^.]+$/,"")+"-compressed.webm");updateStatus("video-compressor","Done — original stayed in your browser.");
}

function wireTools(): void {
  document.querySelectorAll<HTMLInputElement>("[data-input]").forEach(input=>input.addEventListener("change",async()=>{const file=input.files?.[0],tool=input.dataset.input as ToolId|undefined;if(!file||!tool||state[tool])return;if(tool==="remove-bg"&&!document.querySelector<HTMLInputElement>('[data-consent="remove-bg"]')?.checked){updateStatus(tool,"Please accept the processing notice before uploading.");input.value="";return;}state[tool]=true;try{if(tool==="remove-bg")await removeBackground(file);else if(tool==="image-compressor")await compressImage(file);else await compressVideo(file);}catch(error){updateStatus(tool,error instanceof Error?error.message:"Something went wrong.");}finally{state[tool]=false;input.value="";}}));
  document.querySelectorAll<HTMLElement>(".reveal").forEach(el=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){(e.target as HTMLElement).classList.add("visible");observer.unobserve(e.target);}}),{threshold:.1});observer.observe(el);});
}
function mount(): void {
  const route=normalizePath(); let content:string;
  if(route==="/")content=home(); else if(route==="/remove-bg")content=toolPage("remove-bg","Remove Background","Remove the background from your image with FlyThe BG's protected AI workflow.","image/png,image/jpeg,image/webp","PNG · JPG · WEBP · max 15 MB","Only this tool sends your selected image to the protected processing service.");
  else if(route==="/image-compressor")content=toolPage("image-compressor","Compress Image","Shrink an image directly in your browser without uploading the original.","image/*","Local processing · no upload","Your original image stays in your browser.");
  else if(route==="/video-compressor")content=toolPage("video-compressor","Compress Video","Reduce video size locally using browser MediaRecorder support.","video/*","Local processing · WebM output","Your original video stays in your browser.");
  else if(route==="/features")content=features(); else if(route==="/about")content=about(); else if(route==="/faq")content=faq(); else if(route==="/privacy")content=privacy(); else if(route==="/terms")content=terms(); else content=contact();
  const app=document.getElementById("app"); if(app)app.innerHTML=content; wireTools();
}
mount();
