import type { Metadata } from "next";
import Link from "next/link";
import { WatermarkRemover } from "@/components/WatermarkRemover";

export const metadata: Metadata = {
  title: "Gemini Watermark Remover — Image & Video Tool",
  description: "A browser-first Gemini watermark remover for images, with Meta AI support and a video preview workflow. Process selected media locally in your browser.",
  keywords: ["gemini watermark remover", "gemini watermark remover online", "remove gemini watermark", "gemini image watermark remover", "gemini video watermark remover", "meta ai watermark remover", "AI watermark remover", "watermark remover"],
  alternates: { canonical: "/ai-watermark-remover" },
  openGraph: { title: "Gemini Watermark Remover — FlytheBG", description: "Browser-first image and video watermark utility with separate Gemini and Meta AI labels.", url: "/ai-watermark-remover", type: "website" },
};

const faqs = [
  ["Is this a Gemini watermark remover?", "Yes. FlytheBG provides an independent watermark-removal workspace that can be labelled for Gemini, Meta AI, or both/other AI sources. The Gemini wording is used so people searching for Gemini watermark remover can find the relevant tool page."],
  ["Does FlytheBG belong to Google or Meta?", "No. FlytheBG is independent. Gemini is a Google product and Meta AI is a Meta product. Their names and marks belong to their respective owners; FlytheBG does not imply affiliation or endorsement."],
  ["Does the tool work with video?", "The workspace accepts video and provides a local preview-frame cleanup workflow. Full frame-by-frame video reconstruction can be memory-intensive, so the browser tool deliberately avoids silently freezing a user's device."],
  ["Can I stop a watermark before it is created?", "For new Gemini image generations on the web, Google may provide a visible-watermark setting in account settings. That setting only applies to future creations and does not remove marks from files you already saved. Availability and wording can change, so check Gemini's current settings/help when using that option."],
  ["What if I do not like the result?", "Do not publish the output blindly. Try a tighter watermark area, choose the correct corner preset, use the original source where possible, or keep the original media. Reconstruction can fail on detailed backgrounds, gradients, faces, text, or moving video scenes."],
];

export default function AiWatermarkRemoverPage() {
  return (
    <main className="featurePage watermarkPage">
      <section className="pageHero compactHero"><div className="shell narrowHero"><span className="eyebrow"><i/> AI watermark remover</span><h1>Gemini Watermark Remover for Images & Video.</h1><p>Search for Gemini, choose the source label that matches your media, and work in one themed browser-first tool. Meta AI is supported in the same workspace but is labelled separately so visitors can tell which AI ecosystem they are working with.</p><div className="heroProof inline"><span><strong>Gemini</strong><small>image workflow</small></span><span><strong>Meta AI</strong><small>separate source label</small></span><span><strong>Video</strong><small>local preview workflow</small></span></div></div></section>
      <section className="toolWorkspace"><div className="shell"><WatermarkRemover /></div></section>
      <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> One tool, clear labels</span><h2>Choose the AI source instead of hiding it.</h2><p>Gemini and Meta AI use one shared FlytheBG interface because the visitor workflow is the same: select media, identify the watermark area, reconstruct the selected pixels locally, and inspect the result. The source selector keeps the brands visibly separate for clarity and search intent.</p></div><div className="principleList"><article><strong>Gemini Watermark Remover</strong><p>The page is explicitly titled around the phrase people use when looking for a Gemini watermark remover. That makes the tool discoverable without pretending FlytheBG is an official Google service.</p></article><article><strong>Meta AI Watermark Remover</strong><p>Meta AI is offered as a separate source label in the same tool. The interface does not combine their names into a fake official product identity.</p></article><article><strong>Results stay on the user's side</strong><p>The selected media is handled in browser memory by this workspace. FlytheBG does not intentionally upload the working file to a FlytheBG image-processing server for this feature.</p></article></div></div></section>
      <section className="section toolInfoSection"><div className="shell infoCards"><article><span>For future generations</span><h2>Turn off visible watermarks when the provider offers that control.</h2><p>If you generate new images inside Google Gemini on the web, look in your Google/Gemini account settings for the current visible media-watermark option. Turning that setting off, where available, affects future generations; it does not remove a watermark from an already-saved image or video.</p><ol><li>Open Gemini Web and sign in.</li><li>Open Settings.</li><li>Look for the current Media watermark / visible watermark control and switch it off if the option is available to your account.</li></ol><p><strong>Note:</strong> provider settings can change. Always follow the current Google documentation and account UI.</p></article><article><span>When you dislike the result</span><h2>Use the original, change the selected area, or stop.</h2><p>Watermark reconstruction is not magic. If the surrounding scene is detailed or the watermark overlaps important content, the result may contain visible artifacts. FlytheBG intentionally tells you to inspect the output rather than promising perfect removal.</p><Link className="textLink" href="/faq">Read the full FAQ ↗</Link></article><article><span>Responsible use</span><h2>Only edit media you are allowed to edit.</h2><p>You are responsible for copyright, privacy, attribution, platform rules, and any rights attached to the media you process. Removing a visible mark does not grant ownership of the underlying content.</p><Link className="textLink" href="/terms">Read Terms of Use ↗</Link></article></div></section>
      <section className="section faqSection" id="faq"><div className="shell"><div className="sectionHeading"><span className="eyebrow"><i/> Watermark remover FAQ</span><h2>Clear answers before you edit.</h2></div><div className="landingFaqGrid">{faqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    </main>
  );
}
