import type { Metadata } from "next";
import Link from "next/link";
import { WatermarkRemoverV2 } from "@/components/WatermarkRemoverV2";

export const metadata: Metadata = {
  title: "Free Gemini Watermark Remover — Image & Video Tool",
  description: "Use a free Gemini watermark remover online for visible Gemini and Veo marks. Browser-first reconstruction uses calibrated selection and local export instead of blurring the whole watermark area.",
  keywords: ["free Gemini watermark remover", "Gemini watermark remover", "gemini watermark remover online", "remove Gemini watermark", "Gemini image watermark remover", "Gemini video watermark remover", "Veo watermark remover", "AI watermark remover", "watermark remover", "visible watermark remover"],
  alternates: { canonical: "/ai-watermark-remover" },
  openGraph: { title: "Free Gemini Watermark Remover — FlyThe BG", description: "Free browser-first visible-watermark editor with calibrated presets, manual selection, preview, and local export.", url: "/ai-watermark-remover", type: "website" },
};

const faqs = [
  ["Where is the Gemini watermark?", "The visible Gemini sparkle is commonly placed in the lower-right area. Fly The BG uses calibrated geometry rather than an old percentage-based guess, then shows the exact selection box in the preview."],
  ["Can I move the fixed selection?", "Yes. Use Position X/Y and Size scale, or drag directly over the mark to create a manual selection. This keeps the tool useful if a provider changes its export layout."],
  ["Does the image get blurred?", "The Gemini/Veo path uses reverse-alpha reconstruction instead of Gaussian blur or generative inpainting. Use Preview result first so you can inspect the actual pixels before downloading."],
  ["Does it support any image ratio?", "Yes. Geometry is calculated from the uploaded media dimensions, so portrait, square, landscape, and unusual aspect ratios are supported."],
  ["Does it work with Veo video?", "Yes. The selected fixed region is reconstructed frame-by-frame and exported as WebM where the browser supports MediaRecorder."],
  ["What about Meta AI?", "Older Meta AI generations used visible corner labels. The tool provides an editable lower-right legacy preset for those visible marks. Newer Meta Content Seal is an invisible provenance system and is not a visible pixel watermark that this editor can remove."],
  ["Does it remove SynthID or Content Seal?", "No. Google describes SynthID as an invisible watermark, and Meta describes Content Seal as an invisible provenance signal. This tool targets visible pixel overlays only."],
  ["Is processing local?", "The watermark reconstruction and preview run in browser memory. Software/reference assets may still be downloaded by the browser, and optional site analytics or advertising can make separate network requests."],
];

export default function AiWatermarkRemoverPage() {
  return <main className="featurePage watermarkPage">
    <section className="pageHero compactHero"><div className="shell narrowHero"><span className="eyebrow"><i/> Free Gemini Watermark Remover</span><h1>Remove visible Gemini &amp; Veo watermarks from images and video.</h1><p>Use a free Gemini watermark remover online with calibrated fixed-position presets, direct selection, before-and-after preview, and local browser export — without blurring the whole watermark area.</p><div className="heroProof inline"><span><strong>Gemini / Veo</strong><small>calibrated visible mark</small></span><span><strong>Manual selection</strong><small>adjust position + size</small></span><span><strong>Local export</strong><small>preview before download</small></span></div></div></section>
    <section className="toolWorkspace" id="watermark-tool"><div className="shell"><WatermarkRemoverV2 /></div></section>
    <section className="section"><div className="shell workflowGrid"><div className="sectionHeading compact"><span className="eyebrow"><i/> Simpler controls</span><h2>Start with the known position, then adjust only if needed.</h2><p>The previous blind percentage guess has been replaced with provider-aware fixed geometry. The red box is visible before processing, and manual drag selection remains available when a source uses a different layout.</p></div><div className="principleList"><article><strong>Calibrated geometry</strong><p>Gemini/Veo placement is calculated from the actual media dimensions using a calibrated geometry approach.</p></article><article><strong>No blur pass</strong><p>The Gemini/Veo reconstruction uses reverse-alpha math with reference masks instead of blurring the surrounding scene.</p></article><article><strong>Before export</strong><p>For images, Preview result generates a smaller comparison so you can inspect the cleaned region before downloading the full export.</p></article><article><strong>Local processing</strong><p>Image reconstruction and browser video processing run in local browser memory. Long or high-resolution videos can still use substantial CPU and memory.</p></article></div></div></section>
    <section className="section toolInfoSection"><div className="shell infoCards"><article><span>Provider changes</span><h2>The box is adjustable on purpose.</h2><p>Watermark dimensions and margins can change between model generations, export surfaces, and resolutions. Use the visible box, Size scale, and Position controls rather than assuming every future output will match one sample.</p></article><article><span>Invisible provenance</span><h2>Visible removal is not provenance removal.</h2><p>Google&apos;s SynthID and newer Meta provenance systems are designed to be invisible. FlyThe BG does not claim to remove or defeat those systems.</p></article><article><span>Responsible use</span><h2>Only edit media you are allowed to edit.</h2><p>You remain responsible for copyright, privacy, attribution, platform rules, and any rights attached to the media.</p><Link className="textLink" href="/terms">Read Terms of Use ↗</Link></article></div></section>
    <section className="section wmMethodsSection"><div className="shell"><div className="sectionHeading compact"><span className="eyebrow"><i/> Two ways to handle Gemini watermarks</span><h2>Remove an existing visible watermark or turn it off for future creations.</h2><p>Choose the method that matches your situation. The first method is for media you already have; the second is a provider setting for future Google Gemini image creations when the option is available to your account.</p></div><div className="wmMethodsGrid"><article className="wmMethodCard"><span className="wmMethodNumber">01</span><h3>Instant Online Tool</h3><h4>Remove Gemini Watermark from Existing Images &amp; Veo Videos</h4><p>For existing Google Gemini (Imagen) photos or Veo AI videos, use the remover above. It works in your browser and is designed around mathematical visible-mark reconstruction rather than whole-image blur.</p><ol><li><strong>Upload Media:</strong> Drag &amp; drop a Gemini image (PNG, JPG, WebP) or Veo video (MP4, MOV) into the remover above.</li><li><strong>Mathematical Unblending:</strong> The engine applies reverse-alpha reconstruction to unblend the visible watermark instead of using blurry AI inpainting.</li><li><strong>Export Clean File:</strong> Use Preview result first, then click Remove &amp; Export to download the processed file locally.</li></ol><a className="wmMethodLink" href="#watermark-tool">Use Free Gemini Watermark Remover ↗</a></article><article className="wmMethodCard"><span className="wmMethodNumber">02</span><h3>Gemini Account Settings</h3><h4>Turn Off Watermarks for Future AI Generations</h4><p>If Google Gemini currently exposes a visible/media watermark setting for your account, you can disable it for new image creations from Gemini&apos;s settings.</p><ol><li><strong>Go to Gemini Web:</strong> Open <a href="https://gemini.google.com/">gemini.google.com</a> and sign in.</li><li><strong>Open Settings:</strong> Select the Settings gear in the Gemini menu or sidebar.</li><li><strong>Toggle Off:</strong> Look for the current <em>Media watermark</em> or visible-watermark control and switch it off when Google provides that option.</li></ol><p className="wmMethodNote"><strong>Note:</strong> This only affects future image creations. It cannot remove watermarks from already-saved files or Veo videos. Google can change account settings and availability, so follow the current Gemini interface.</p></article></div></div></section>
    <section className="section faqSection" id="faq"><div className="shell"><div className="sectionHeading"><span className="eyebrow"><i/> Watermark remover FAQ</span><h2>Clear answers before you edit.</h2></div><div className="landingFaqGrid">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
  </main>;
}
